# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: E2E and build testing.

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ github.head_ref }}
    - run: echo "::set-env name=TAGS_JSON::$(curl -sb -H https://registry.hub.docker.com/v1/repositories/dmsc/duo-backend/tags)"
    - run: echo "TAGS_JSON $TAGS_JSON"
    - run: echo "::set-env name=TAG_COUNT::$(echo $TAGS_JSON | jq --arg GITHUB_REF_NAME_SLUG '${{ github.head_ref }}' -c '.[] | select(.name==\'test-params\')' | jq -s '. | length')"
    
