# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test && Build

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: FranzDiebold/github-env-vars-action@v1.2.0
    - run: echo "CI_COMMIT_BRANCH $GITHUB_REF_NAME_SLUG"
    - run: echo "::set-output name=TAGS_JSON::$(curl -sb -H https://registry.hub.docker.com/v1/repositories/dmsc/duo-backend/tags)"
    - run: echo "outputs.TAGS_JSON $outputs.TAGS_JSON"
    - run: echo "outputs.TAGS_JSON ${outputs.TAGS_JSON}"
    - run: echo "outputs.TAGS_JSON ${outputs}.TAGS_JSON"
    - run: TAG_COUNT=$(echo $TAGS_JSON | jq --arg "GITHUB_REF_NAME_SLUG" $GITHUB_REF_NAME_SLUG -c '.[] | select(.name==$GITHUB_REF_NAME_SLUG)' | jq -s '. | length')
    - run: echo "TAG_COUNT $TAG_COUNT"
    - run: if [ "$TAG_COUNT" != 0 ]; then    echo "::set-env name=TAG::$GITHUB_REF_NAME_SLUG"; else    echo "::set-env name=TAG::latest"; fi
    - run: echo "TAG $TAG"
