name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop and master branches
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "action ${{ github.action }}"
      - run: echo "action_path ${{ github.action_path }}"
      - run: echo "actor ${{ github.actor }}"
      - run: echo "base_ref ${{ github.base_ref }}"
      - run: echo "event ${{ github.event }}"
      - run: echo "event.before ${{ github.event.before }}"
      - run: echo "event.after ${{ github.event.after }}"
      - run: echo "event_name ${{ github.event_name }}"
      - run: echo "event_path ${{ github.event_path }}"
      - run: echo "head_ref ${{ github.head_ref }}"
      - run: echo "job ${{ github.job }}"
      - run: echo "ref ${{ github.ref }}"
      - run: echo "repository ${{ github.repository }}"
      - run: echo "repository_owner ${{ github.repository_owner }}"
      - run: echo "run_id ${{ github.run_id }}"
      - run: echo "run_number ${{ github.run_number }}"
      - run: echo "sha ${{ github.sha }}"
      - run: echo "workflow ${{ github.workflow }}"
      - run: echo "workspace ${{ github.workspace }}"
